### ISSUE TITLE
Add .storage() method?

### ISSUE THREAD

**Issue by thomasfoster96** [coderhaoxin/typed-objects#13]
Firefox Nightly Typed Objects implementation includes a storage method which can be used to get the backing buffer for a typed object. It doesn't appear that this library has such a method - is this intentional or is Firefox deviating from the draft spec?

**Comment by RReverser** [comment]
See https://github.com/coderhaoxin/typed-objects/blob/master/test/index.js#L218. I also didn't notice it in the first place :)

**Comment by thomasfoster96** [comment]
So it's a method on the TypedObject's type class (is that what they're called?!)?

**Comment by RReverser** [comment]
@thomasfoster96 Given that I can't find it in https://github.com/dslomov/typed-objects-es7, I'm not even sure it's official one.

**Comment by thomasfoster96** [comment]
You're right, there's no `.storage()` method there, but there is one on ES Wiki: http://wiki.ecmascript.org/doku.php?id=harmony:typed_objects

Firefox seems to be following the wiki rather than the Github repo. 

Oh, and [this presentation](https://docs.google.com/presentation/d/1HGoxjX74Q9i8I1ok-hkmxzWlM7CDQwxT0sUS5PJDxdg/edit#slide=id.g29e43d8ba_05) to the TC39 committee says that there is instead a `.buffer` property on each individual object.

:confused:

**Comment by RReverser** [comment]
ES Wiki is pretty outdated, better not to use it as source of truth.

**Comment by RReverser** [comment]
Presentation is also dated 1.5 years ago... But probably better to ask @dslomov.

**Comment by thomasfoster96** [comment]
Yeah, agree re: age of sources. Otherwise, in the meantime is it worth following the Firefox implementation or is this package going to strictly follow the draft spec?

**Comment by RReverser** [comment]
I don't think it's worth following any custom implementation. Apparently this project defines a way to access storage in the absence of other methods, as well as Firefox does, but if you want to use this as a polyfill and not library on its own, better to wait for clarifications. But in fact, I don't think that it can be property on the object itself, as in that case it would collide with same-named custom property if defined in struct itself.

**Comment by dslomov** [comment]
The idea was to have a buffer() method "somewhere" (only work for transparent typed objects of course). I do not think we ever had a final decision on where to put it.
That said, I am no longer working on Javascript at Google, so this spec needs a real owner - try @littledan.

**Comment by thomasfoster96** [comment]
@RReverser sounds reasonable - if I can't get a clarification soon I might fork this repo and follow the Firefox implementation quirks.

@dslomov is @littledan looking after the Typed Objects spec now?

**Comment by RReverser** [comment]
> if I can't get a clarification soon I might fork this repo and follow the Firefox implementation quirks

Why do you think it's a good idea to follow dangerous quirk? (which, as I said, is bad since can cause conflicts in code)

**Comment by RReverser** [comment]
Btw mentioned wiki also defines methods that this repo represents:

> The following operations on typed objects expose storage:

>    buffer(object) : ArrayBuffer or null : the buffer containing the backing storage for the array
    byteOffset(object) : integer or undefined : the byte offset in the buffer at which the array data begins
    byteLength(object) : integer or undefined : the number of bytes of the buffer consumed by the array
    storage(object) : takes an instance of the struct type and produces an object containing the above three properties.

**Comment by thomasfoster96** [comment]
> Why do you think it's a good idea to follow dangerous quirk? (which, as I said, is bad since can cause conflicts in code)

As far as I can tell, Firefox is doing something along the line of what the wiki describes (the `TypedObject.storage()` method returns an objects with properties (`buffer`, `byteOffset`, `byteLength`). The [dslomov/typed-objects-es7](https://github.com/dslomov/typed-objects-es7) repo doesn't mention a `.storage()` method anywhere. Unless there is a right way to get a buffer from a typed object, the Firefox behaviour is what I'd temporarily adopt (so there's not two quirks out there).

**Comment by littledan** [comment]
@thomasfoster96 Typed Objects are not currently really on a standards track. I plan to get this program back on it, but focusing initially on value types, which inherently don't have a backing store. I think there's still a lot of work ahead for Typed Objects, and wouldn't assume that the standardized version will look like the current draft version. In particular, I'm skeptical of the need for the parallel type system that the Typed Objects draft introduces. Also, any method names signatures may change.

Is there anyone in Mozilla who might want to work on Typed Objects with me? Or, does anyone have more requests for what Typed Objects or value types should support? Is this method very important?

**Comment by RReverser** [comment]
> Is there anyone in Mozilla who might want to work on Typed Objects with me?

@littledan I'd love to help with spec, since that would help my projects like https://github.com/jDataView/jBinary and, inherently, http://rreverser.github.io/mpegts/, but I'm not in Mozilla :(

**Comment by littledan** [comment]
@RReverser Well, sorry for phrasing my question in such a restricted way, I'd be happy to have your help. I'll get back to you when I'm in a more concrete phase of this. I'm getting off-topic, but would you be interested in 64-bit integers too, if you're working on those related projects?

**Comment by RReverser** [comment]
No problem. 64-bit integers are sure interesting, but aren't they rather related to pure Value Objects? (it's hard to figure out where one ends and another begins)

**Comment by littledan** [comment]
Yes, they are, as is SIMD.js. But as the progress of SIMD is showing, you can do one without the other if needed. It's all an interconnected program ideally though. Ideally 64-bit integers and SIMD vectors are  value objects.

**Comment by thomasfoster96** [comment]
@littledan Is there an explainer somewhere as to how 64-bit integers and SIMD are currently interconnected? I feel as though I'm missing about six months of progress, and if I could get myself up to speed with what's happened I'd be happy to give some help (like @RReverser, I've got some projects that would really be helped by these proposals).

**Comment by littledan** [comment]
@thomasfoster96 I'll write one up within a couple months. I have some extremely rough notes at https://github.com/littledan/value-spec/wiki but I'll get something better. Basically, they are both cases of new, immutable primitives, and value types could generalize/explain that. Further, I plan to propose that value types be the basis for user-defined operator overloading (but that's a separate proposal on top).

**Comment by thomasfoster96** [comment]
@littledan thanks for the link to the wiki, and I'll look out for the explainer in a few months.
